# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"
    resolvers:
        default:
            web_path: {}
    filter_sets:
        galerie:
            filters:
                relative_resize:
                    widen: 360